@echo off
echo Stopping any existing containers...
docker-compose down 2>nul
echo Starting Docker cluster...
docker-compose up -d
echo Waiting 20 seconds for services to initialize...
timeout /t 20 /nobreak >nul
echo Installing Python dependencies...
docker exec --user root wiki-spark-master pip3 install -r /app/requirements.txt -q
echo Running pipeline...
docker exec --user root -e PYTHONPATH="/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip" -w /app wiki-spark-master python3 /app/main.py
echo Cleaning up temporary files...
for /d /r . %%d in (__pycache__) do @if exist "%%d" rd /s /q "%%d"
del /s /q *.pyc 2>nul
echo Pipeline complete. Results in output\ folder.
pause
